# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_accountBatchcreate(self):
    # Test name: Account_Batch_create
    # Step # | name | target | value
    # 1 | open | /account/create | 
    self.driver.get("https://testurl url removed for corporte security")
    # 2 | setWindowSize | 1216x1370 | 
    self.driver.set_window_size(1216, 1370)
    # 3 | click | css=.btn__sub:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn__sub:nth-child(2)").click()
    # 4 | click | css=.btn__white > span:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn__white > span:nth-child(1)").click()
    # 6 | click | css=.h-\[36px\] | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-\\[36px\\]").click()
    # 7 | type | css=.h-\[36px\] | test1
    self.driver.find_element(By.CSS_SELECTOR, ".h-\\[36px\\]").send_keys("test1")
    # 8 | click | css=.button--save | 
    self.driver.find_element(By.CSS_SELECTOR, ".button--save").click()
    # 9 | click | css=.btn__orange | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn__orange").click()
    # 10 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
  
